# non-adjustable variables (change at your own risk)
SLIDERS_STARTING_VALUE = 1
SLIDERS_STEP = 1
RANDOM_STATE = 42
TRAIN_SPLIT_SLIDER_STARTING_VALUE = 10
TRAIN_SPLIT_SLIDER_MAX_VALUE = 90
ALTAIR_PLOTS_HEIGHT = 500
ALTAIR_PLOTS_WIDTH = 500

# adjustable variables
## app version
SINGLE_USER_ADVANCED_APP_VERSION = True

## emojis
APP_TITLE = "DartML"
APP_FAVICON = "🎯"
HOME_PAGE_EMOJI = "🏠"
SAMPLE_PAGE_EMOJI = "🧪"
EXPLORE_PAGE_EMOJI = "🔍"
MODIFY_AND_MODEL_PAGE_EMOJI = "🛠️"
ASSESS_PAGE_EMOJI = "📊"

## pages titles
SEMMA_COLOR = "red"
HOME_PAGE_TITLE = f"{HOME_PAGE_EMOJI} Home"
SAMPLE_PAGE_TITLE = f"{SAMPLE_PAGE_EMOJI} Sample"
EXPLORE_PAGE_TITLE = f"{EXPLORE_PAGE_EMOJI} Explore"
MODIFY_AND_MODEL_PAGE_TITLE = f"{MODIFY_AND_MODEL_PAGE_EMOJI} Modify & Model"
ASSESS_PAGE_TITLE = f"{ASSESS_PAGE_EMOJI} Assess"
SAMPLE_PAGE_TITLE_WITH_COLOR = f"{SAMPLE_PAGE_EMOJI} :{SEMMA_COLOR}[S]ample"
EXPLORE_PAGE_TITLE_WITH_COLOR = f"{EXPLORE_PAGE_EMOJI} :{SEMMA_COLOR}[E]xplore"
MODIFY_AND_MODEL_PAGE_TITLE_WITH_COLOR = (
    f"{MODIFY_AND_MODEL_PAGE_EMOJI} :{SEMMA_COLOR}[M]odify & :{SEMMA_COLOR}[M]odel"
)
ASSESS_PAGE_TITLE_WITH_COLOR = f"{ASSESS_PAGE_EMOJI} :{SEMMA_COLOR}[A]ssess"

# files names in temporary directory
DATA_FILENAME = "sampled_df.csv"
TRAINING_PARAMETERS_FILENAME = "training_parameters.json"
REPORT_DIRECTORY_NAME = "report"

# assess page config
ASSESS_REFRESH_INTERVAL = 2  # in seconds
ASSESS_REFRESH_OVERHEAD = 20  # in seconds
LOGS_FILENAME = "automl_logs.txt"
